// <auto-generated />
using System;
using GraduationAuction.API.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduationAuction.API.Persistance.Data.Migrations
{
    [DbContext(typeof(webDbContext))]
    [Migration("20250429160558_refactor")]
    partial class refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("raduationAuction.API.Model.Auction", b =>
                {
                    b.Property<int>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionID"));

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("itemid")
                        .HasColumnType("int");

                    b.HasKey("AuctionID");

                    b.HasIndex("UserId");

                    b.HasIndex("itemid")
                        .IsUnique();

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Bidding", b =>
                {
                    b.Property<int>("BiddingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BiddingID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Auctionid")
                        .HasColumnType("int");

                    b.Property<DateTime>("BidTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("BiddingID");

                    b.HasIndex("Auctionid");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("raduationAuction.API.Model.BuyerPayment", b =>
                {
                    b.Property<int>("BuyerUserID")
                        .HasColumnType("int");

                    b.Property<int>("BiddingID")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BuyerUserID", "BiddingID");

                    b.HasIndex("BiddingID");

                    b.HasIndex("UserId");

                    b.ToTable("BuyerPayments");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pictureURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("raduationAuction.API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Auction", b =>
                {
                    b.HasOne("raduationAuction.API.Model.User", "User")
                        .WithMany("Auctions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("raduationAuction.API.Model.Item", "item")
                        .WithOne("Auction")
                        .HasForeignKey("raduationAuction.API.Model.Auction", "itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("item");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Bidding", b =>
                {
                    b.HasOne("raduationAuction.API.Model.Auction", "auction")
                        .WithMany("biddings")
                        .HasForeignKey("Auctionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("auction");
                });

            modelBuilder.Entity("raduationAuction.API.Model.BuyerPayment", b =>
                {
                    b.HasOne("raduationAuction.API.Model.Bidding", null)
                        .WithMany("BuyerPayment")
                        .HasForeignKey("BiddingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("raduationAuction.API.Model.User", null)
                        .WithMany("buyerPayments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Item", b =>
                {
                    b.HasOne("raduationAuction.API.Model.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Auction", b =>
                {
                    b.Navigation("biddings");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Bidding", b =>
                {
                    b.Navigation("BuyerPayment");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("raduationAuction.API.Model.Item", b =>
                {
                    b.Navigation("Auction")
                        .IsRequired();
                });

            modelBuilder.Entity("raduationAuction.API.Model.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("buyerPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
